version: '3'
services:
  psql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_DATABASES=db1,db2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./data.sh:/docker-entrypoint-initdb.d/data.sh
volumes:
  db:
    driver: local
