alias ll="ls -lat"
alias subl="${HOME}/bin/subl"
alias ssubl="sudo ${HOME}/bin/subl"
alias activate="source venv/bin/activate"
alias env="source .env"
alias a="subl ${HOME}/.bash_aliases"
alias b="subl ${HOME}/.bashrc"
alias c="subl ${HOME}/.accounts"
alias d="cd ${HOME}/Downloads"
alias k="sudo kill -9"
alias h="cd ${HOME}/"
alias u="subl ${HOME}/.bash_utils"
alias v="cd /Volumes/"
alias p="cd ${_PROJECTS_DIR}"
# --- source profile --------------------------------------------------
alias .a="source ${HOME}/.bash_aliases"
alias .b="source ${HOME}/.bashrc"
alias .u="source ${HOME}/.bash_utils"
# --- Static Websites -------------------------------------------------
alias sph="s3_website push"
alias serve="jekyll serve"
alias serve="bundle exec jekyll serve --trace"
alias sync="rm_dotstore 2>&1 ; bash s3_sync"
# --- Python ----------------------------------------------------------
alias python="/usr/local/bin/python3.7"
alias pip="python -m pip"
alias wpy="which python"
# --- System ----------------------------------------------------------
alias bins="cd ${HOME}/bin && ll"
alias hosts="subl /etc/hosts"
alias skeys="cd ${HOME}/.ssh && ll"
alias keys="subl ${HOME}/.ssh/config && subl ${HOME}/.aws/"
alias killd="sudo launchctl unload -w"
alias killa="launchctl unload -w"
alias unarchive="tar -xzvf" # Unarchive
# --- Git ------------------------------------------------------------
alias gl="git status"
alias gb="git branch"
alias gr="git remote -v"
alias gsts="git status"
alias gadd="git add"
alias gddu="git add -u"
alias gcmm="git commit -m"
alias gph="git push -u"
alias gpll="git pull"
alias gck="git checkout"
alias gmg="git merge"
alias gbrch="git branch"
alias glog="git log --pretty=oneline"
alias gr="git remote -v"
alias gremo="git remote -v"
alias scs="screen -S"
alias scr="screen -r"
# --- Process & Network ----------------------------------------------
alias netop="sudo nettop"
alias aps="sudo ps -efc | sort -k 1 -r" # lists information about all running processes.
alias nps="ps -efc | grep"
alias eps="sudo ps -ceo pcpu,pid,user,args | sort -k 1" # Get process gathering most of the CPU load
alias procs="sudo ps -ceo pcpu,pid,user,args | sort -k 1"
alias sof="sudo lsof -Pni"
alias net="sudo netstat -atln"
alias wps="watch -n 3 'sudo ps -ceo pcpu,pid,user,args | sort -k 1 -r'"
alias wsof="watch -n 1 'sudo lsof -Pni'"
alias wnet="watch -n 1 'sudo netstat -atln'"
alias indomain="curl -sILk"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
